greeting:
  message: "hello"
mp:
  messaging:
    outgoing:
      words-out:
        topic: "words"
    incoming:
      words-in:
        auto:
          offset:
            reset: "earliest"
        topic: "words"
      incomingTopic:
        topic: "quotes"
        auto:
          offset:
            reset: "earliest"

quarkus:
  http:
    port: 8086
